CREATE TABLE public.cadastros (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tipo text NOT NULL CHECK (tipo IN ('dhz','moinho','responsavel')), nome text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tipo,nome));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cadastros TO anon, authenticated;
GRANT ALL ON public.cadastros TO service_role;
ALTER TABLE public.cadastros ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso publico" ON public.cadastros FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE TABLE public.registros_moinho (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), data date NOT NULL DEFAULT CURRENT_DATE, hora time NOT NULL DEFAULT CURRENT_TIME, moinho text NOT NULL, set_point numeric, vazao numeric, produto text, nome_resp text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.registros_moinho TO anon, authenticated;
GRANT ALL ON public.registros_moinho TO service_role;
ALTER TABLE public.registros_moinho ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso publico" ON public.registros_moinho FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
ALTER TABLE public.registros_producao ADD COLUMN dhz_nome text;